[build]
  base = "curatio-final-main/Desktop/pruebafinalcuratio/CURATIO.SOLO.FALTA.SUPABASE-main"
  publish = "curatio-final-main/Desktop/pruebafinalcuratio/CURATIO.SOLO.FALTA.SUPABASE-main/dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 