[build]
  command = "cd CURATIO.SOLO.FALTA.SUPABASE-main && npm install && npm run build"
  publish = "CURATIO.SOLO.FALTA.SUPABASE-main/dist"
  base = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 