[build]
  base = "Desktop/pruebafinalcuratio"
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.11.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 